apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/routing

components:
  - ../production

patches:
  - target:
      kind: Service
      name: sashiko-service
    patch: |-
      - op: add
        path: /spec/selector
        value:
          app: sashiko
