name: Tag Release Workflow
on:
  push:
    tags:
      - 'v*'

jobs:
  check-sob:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Check Developer Certificate of Origin (S-O-B)
        run: make sob RANGE="${{ github.sha }}~1..${{ github.sha }}"

  lint:
    needs: check-sob
    uses: ./.github/workflows/linting.yml

  run-tests:
    needs: [check-sob, lint]
    uses: ./.github/workflows/unit-tests.yml

  integration-tests:
    needs: [check-sob, lint, run-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Setup Rust Cache
        uses: Swatinem/rust-cache@v2
      - name: Run Integration Test
        run: make integration-test
